const ActionTypes = {
    SHOW_ERROR: "SHOW_ERROR",
    USER: "USER",
    VERIFICATION_PHONEID_AND_UID: "VERIFICATION_PHONEID_AND_UID",
    ALL_CONTACTS:"ALL_CONTACTS",
    INITIALIZE_STATES: "INITIALIZE_STATES",
    HIDE_ERROR:"HIDE_ERROR",
    LOADER_START:'LOADER_START',
    LOADER_STOP:'LOADER_STOP',
}

export default ActionTypes;